apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-config
  namespace: flux-system
spec:
  interval: 10m
  path: "./platform/istio"
  prune: false
  sourceRef:
    kind: GitRepository
    name: mkloudlab
    namespace: flux-system
  dependsOn:
    - name: networking
