apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-config
  namespace: flux-system
spec:
  interval: 10m
  path: "./platform/networking/metallb-config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: mkloudlab
    namespace: flux-system
  dependsOn:
    - name: networking
