apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - alloy-daemonset.yaml

configMapGenerator:
  - name: alloy-config
    files:
      - alloy.river=config/alloy.river

generatorOptions:
  disableNameSuffixHash: true
