apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - metallb/source.yaml
  - metallb/helmrelease.yaml
  - external-dns/source.yaml
  - external-dns/helmrelease.yaml
