apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minio-tenant.yaml
  - services.yaml
  - gateway.yaml
  - certificate.yaml
  - destinationrule.yaml
  - networkpolicy.yaml
