# Kustomization for Keycloak
# This file is required for Flux to properly sync the directory
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak.yaml
  - keycloak-gateway.yaml
  - keycloak-cert.yaml
  - keycloak-destinationrule.yaml
  - keycloak-networkpolicy.yaml
